### ISSUE TITLE
KeyError: 'AMAZON_USER'

### ISSUE THREAD

**Issue by RedHatter** [tobiasmcnulty/amzscraper#5]
Any attempt to run amzscraper gives me the following.
```
Traceback (most recent call last):
  File "/home/ava/.pyenv/versions/3.8.3/bin/amzscraper", line 11, in <module>
    load_entry_point('amzscraper==1.0.0', 'console_scripts', 'amzscraper')()
  File "/home/ava/.pyenv/versions/3.8.3/lib/python3.8/site-packages/amzscraper.py", line 287, in main
    args = vars(parse_args())
  File "/home/ava/.pyenv/versions/3.8.3/lib/python3.8/site-packages/amzscraper.py", line 225, in parse_args
    default=os.environ["AMAZON_USER"],
  File "/home/ava/.pyenv/versions/3.8.3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AMAZON_USER'
```

**Comment by nicjohnston** [comment]
@RedHatter Did you ever find a fix for this?  I just ran into the same issue as you with python 3.9

**Comment by RedHatter** [comment]
I did not. Though I didn't try very hard to solve it.

**Comment by nicjohnston** [comment]
I should have followed up on this a long time ago, but I was able to fix the problem by removing a handful of lines.
Forked this after updating some syntax for compatibility with recent selenium versions: https://github.com/nicjohnston/amzscraper
